using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Migrations
{
    /// <inheritdoc />
    public partial class FixMissingTables : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""Comments"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""NewsId"" integer NOT NULL,
                    ""UserId"" integer NOT NULL,
                    ""Content"" text NOT NULL,
                    ""CreatedAt"" timestamp without time zone NOT NULL,
                    CONSTRAINT ""PK_Comments"" PRIMARY KEY (""Id"")
                );

                CREATE TABLE IF NOT EXISTS ""Favorites"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""NewsId"" integer NOT NULL,
                    ""UserId"" integer NOT NULL,
                    CONSTRAINT ""PK_Favorites"" PRIMARY KEY (""Id"")
                );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
